# Browser Config
browser=chrome
headless=false

# App URL
url=https://www.uber.com

# Test Credentials
email=test@gmail.com
password=Test@1234

# Timeouts
implicit.wait=10
explicit.wait=20

# Screenshot
screenshot.path=./screenshots/

# Report
report.path=./test-output/ExtentReport.html
allure.results.directory=./allure-results/

# Database
db.url=jdbc:mysql://localhost:3306/uberdb
db.username=root
db.password=root

# API Base URL
api.base.url=https://api.uber.com/v1